apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-web-sherezade
  namespace: sbenavente
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: roxsross12/test_web:latest
        name: contenedor-webtest   
